### ISSUE TITLE
Allow custom RoR2 install locations

### ISSUE THREAD

**Issue by reedrw** [Foldex/r2mod_cli#1]
This script assumes that Risk of Rain 2 is installed to `$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Risk of Rain 2` or `$HOME/.local/share/Steam/steamapps/common/Risk of Rain 2` and as a result will not if Risk of Rain 2 is installed to a different location (in my case, I keep my steam library on a separate drive).

I've temporarily solved the problem by symlinking my install to `$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Risk of Rain 2`, but it would be nice if there was an option to specify the install location

**Comment by Foldex** [comment]
Added an environment variable that you can set for a custom install location: c4f36121df843c9588324b5ca2477949f01daa65
