### ISSUE TITLE
Feature request: ability to disable mods one by one

### ISSUE THREAD

**Issue by AppleSeed2010** [Foldex/r2mod_cli#13]
Hi,

Can you add the ability to disable only a selected mod ?

Currently, I have just created a plugins_disabled folders on BepInEx root folder and move them manually from/too plugins folder.

It will be nice if the plugins from the disabled folder can be updated too. (Usefull when waiting for a plugin fix for a new version of the game).

Thanks you.
Regards,

**Comment by AppleSeed2010** [comment]
Hi,

You will find a patch for disable/enable mods by name. This patch need testing (for the update mods part) and probably some corrections.
[r2mod_disabler.patch.txt](https://github.com/Foldex/r2mod_cli/files/6217303/r2mod_disabler.patch.txt)
With this patch, the plugins folder are listed by install date (ls -tr) : this will give some tracking help when we install a bunch of Mods at once, and the game do not work correctly anymore. 

This patch add an ini file support too, linked to the issue [14](https://github.com/Foldex/r2mod_cli/issues/14).

Regards

**Comment by Foldex** [comment]
I'm not sure I follow the use case here, is there a reason you wouldn't just uninstall a mod you don't want? Reinstalling it if you want it back is easy enough as far as I'm concerned. There are some other questions like should disabled mods even be updated, or included in exported profiles.

As for the config file, I don't think we're at the point where  a lot of configuration is going on that would justify a dedicated config file, so I'd prefer to just stick with one or two environment variables.

**Comment by AppleSeed2010** [comment]
The case (for me) : some plugins not updated for the last version break the games.
I just disable them to let the game work again.
Then, when updating the mods, if one of broken mod is updated, I can see it directly and enable it again.
