### ISSUE TITLE
Env var error if game not in default steam library

### ISSUE THREAD

**Issue by AppleSeed2010** [Foldex/r2mod_cli#14]
Hello,

At the start of r2mod, you check the R2MOD_INSTALL_DIR env var.
Can you check to R2_COMPAT too ?

On my system, I need to force it, because "$HOME/$FLATPAK_DIR/steamapps/compatdata/$STEAM_ID" nor  "$HOME/$STEAM_DIR/steamapps/compatdata/$STEAM_ID" exist.

```
[r2mod_cli]$ export STEAM_ID="632360"; export STEAM_DIR=".local/share/Steam"

[r2mod_cli]$ ls $HOME/$STEAM_DIR/steamapps/compatdata/$STEAM_ID
ls: cannot access '/home/auser/.local/share/Steam/steamapps/compatdata/632360': No such file or directory

[r2mod_cli]$ ls $HOME/$FLATPAK_DIR/steamapps/compatdata/$STEAM_ID
ls: cannot access '/home/auser//steamapps/compatdata/632360': No such file or directory
```

=> My steam library as multiples folders : RoR2 is on an alternate drive.
/media/Data-4-2000/Jeux/.steam_depot_3_wine_steam/steamapps/common/Risk of Rain 2
/media/Data-4-2000/Jeux/.steam_depot_3_wine_steam/steamapps/compatdata/632360

A little dirty patch :
- I put r2mod folder in Risk of Rain 2 folder (personal preference : I don't like to install an not packaged application on the system side)
- created a "r2mod.ini" in the r2mod folder containing the correct exported R2MOD_INSTALL_DIR and R2_COMPAT var. (Maybe the file can be in the ~/.config folder if r2mod installed with make install).
- sourced the r2mod.ini : at line 14
`if [[ -f $(dirname $0)/r2mod.ini ]]; then source $(dirname $0)/r2mod.ini; elif [[ -f ~/.config/r2mod.ini ]]; then source ~/.config/r2mod.ini; fi`
- to check if R2_COMPAT is already assigned, added line 25 (and 33):
`if [[ ! -n "$R2_COMPAT" ]]; then
               ...
fi
`

It will be even better to check the steam configuration file to automatically find the good RoR2 folder, but...

Nice script by the way.
Regards,
OS : Arch Linux.

**Comment by Foldex** [comment]
Should be fixed, only difference is that the ENV var is named `R2MOD_COMPAT_DIR` instead now.
