### ISSUE TITLE
Not an issue, but a question (Font)

### ISSUE THREAD

**Issue by Hi-ImKyle** [Foldex/r2mod_cli#17]
Just wondering what the font is in the preview image

![This](https://raw.githubusercontent.com/Foldex/r2mod_cli/master/img/screen.png)

**Comment by Foldex** [comment]
It's [tewi](https://github.com/lucy/tewi-font), though the repo was archived and bitmap fonts are no longer supported by pango. 
The fork which converted it to a pango supported otb seems to have disappeared itself, but I still have [my copy](https://github.com/Foldex/r2mod_cli/files/6275796/tewi-bdf-otb.zip) around.
[otb-tewi-git](https://aur.archlinux.org/packages/otb-tewi-git/) also seems to have a PKGBUILD for converting the original.
