### ISSUE TITLE
Autocomplete from middle of mod name + case insensitive completion

### ISSUE THREAD

**Issue by Hnaguski** [Foldex/r2mod_cli#2]
Trying to install mods entirely from the command line is a bit of a pain currently, as (at least for me) the zsh completion only matches results from the beginning of the string. For example, if I want to install the [TooManyFriends](https://thunderstore.io/package/wildbook/TooManyFriends/) mod, I type `r2mod install too` then hit tab, but it wouldn't return anything. I'd have to first type `r2mod install wildbook` then hit tab and it would then list all the mods that they've uploaded to thunderstore. 
I'm not sure if this is a configuration error with my own .zshrc or if the zsh completion script could be updated to support this feature. I'd also suggest that case insensitive completion be supported, as it would help with finding mods as well.

**Comment by Foldex** [comment]
Added in 2b80639dd3a556d27807559090857858150ea9e9
Should shore up the zsh side of things, though I'm not sure if bash's completion system allows for anything similar without requiring configuring the shell itself.

As an aside, you can globally enable case-insensitive completions in zsh with:
`zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}'`
in your .zshrc.
