### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by CJendantix** [Foldex/r2mod_cli#25]
where would I change the source to work with native steam, or is there just some sort of option. (I'm compiling from source code)

**Comment by CJendantix** [comment]
I just looked through the source and there doesn't seem to be an easy way to do this. I'm not going to close this because I might be wrong, but this seems like it was made from the ground up for the flatpak version

**Comment by Foldex** [comment]
Not sure I follow, as it supports both already and as a bash script, isn't compiled.

**Comment by CJendantix** [comment]
oh lol im so confused, I compile it with make, but how do I make it use native?

**Comment by CJendantix** [comment]
omg I literally just realized I've been using the word: compile this whole time. talk about wrong terminology lmao. I meant install. (yes I know what make does)

**Comment by CJendantix** [comment]
also I can't find anything in the script that has to do with the native version of steam

**Comment by CJendantix** [comment]
ok i'm very stupid. I have literally no idea why it wasn't working but before it simply didn't install on the native version. thanks for trying to help with a non-problem lol.
