### ISSUE TITLE
Question regarding setup

### ISSUE THREAD

**Issue by seinfeldballs** [Foldex/r2mod_cli#26]
For context I'm using Konsole on Steam Deck, when I try to run "r2mod setup" or any r2mod command it says "bash: r2mod: command not found". This is likely a problem regarding my lack of experience with linux, but would still appreciate the help. Thank you!

**Comment by Foldex** [comment]
> bash: r2mod: command not found

That would imply r2mod isn't installed, what installation method are you using? 
I presume this is probably because the deck has an immutable system, so you cant install to system directories.

**Comment by seinfeldballs** [comment]
I used flatpak to install it

**Comment by seinfeldballs** [comment]
Feel a little embarrassed but as soon as I made that 2nd comment I noticed where it had the alias line and that fixed my problem. Thanks for your help!
