### ISSUE TITLE
launch game option

### ISSUE THREAD

**Issue by bgkillas** [Foldex/r2mod_cli#3]
it may be a bit hard to get it to work with alot of computers but you could maybe just have someone launch the game with the launch options "PROTON_DUMP_DEBUG_COMMANDS=1 %command%" then it would be in /tmp/proton_$USER/run

**Comment by Foldex** [comment]
Added in 6fddaf08c91189910637d86f32c19b67754e8ced
Steam comes with a handy `-applaunch` argument, so we can just pass the gameid and it'll handle the rest.

**Comment by bgkillas** [comment]
ye i forgot also 
steam steam://run/632360
i really forget things some times
