### ISSUE TITLE
Feature request: Multiple profiles

### ISSUE THREAD

**Issue by Cervoxx** [Foldex/r2mod_cli#4]
I'm requesting that the ability to have multiple profiles, where different mods and their configs can be installed to. Allowing you to swap, create, and delete them with ease. As far as I can tell the codes generated by the export command dont last long.

P.S. Don't know where else I can put this so im putting it here, thank you very much for making this mod manager!

**Comment by Foldex** [comment]
> I'm requesting that the ability to have multiple profiles, where different mods and their configs can be installed to. Allowing you to swap, create, and delete them with ease. As far as I can tell the codes generated by the export command dont last long.

I had thought of adding this, as it would be nice to have. It should just be a matter of making dirs somewhere like 
`${XDG_DATA_HOME:-$HOME/.local/share}/r2mod/`, symlinking the active profile to the installation dir,  and adding some commands for managing them.

I am kind of burnt out on risky at the moment though, so not sure when I'll get around to this.
Short term workaround is that old profiles do get backed up  to `/tmp`, so grabbing them from there should be easy.

 >P.S. Don't know where else I can put this so im putting it here, thank you very much for making this mod manager!

👍

**Comment by Foldex** [comment]
Added a very basic implementation for this. It's just using the existing export/import functionality in a persistent location, so the niceties of a more robust method are absent. But it should be sufficient enough for the time being.
